In [52]:
import numpy as np

Broadcasting in Numpy

In [53]:
np.random.rand(4)

array([0.58120733, 0.14267862, 0.94591918, 0.33999059])

In [54]:
np.random.rand(5,5) # Returns a 5 row 5 column array randomly distributed

array([[0.62043546, 0.45295964, 0.23976742, 0.03450459, 0.14859311],
       [0.81086617, 0.65310538, 0.54446869, 0.04119477, 0.46816625],
       [0.88874673, 0.47625856, 0.41248898, 0.61610654, 0.32141655],
       [0.58086926, 0.39661405, 0.02009137, 0.4313959 , 0.41124451],
       [0.62906175, 0.50252189, 0.16212784, 0.66689706, 0.13527229]])

In [55]:
np.random.randn(10) # Returns a mean 0 and standard deviation of 1 - Normal Distribution

array([-0.49267415, -0.5824889 , -0.05838766, -0.44856142,  0.44664157,
        1.21572864,  0.55561041,  0.20866362,  2.25497172, -0.20650797])

In [56]:
np.random.normal(20)

19.419021579187913

In [57]:
np.random.randint(1, 100, 20) # Return a set of random integers starting at 1 and ending at 100 * 20 times

array([ 5, 56, 22, 91, 79, 40, 37, 24, 95, 36, 52, 18, 47, 14, 31, 50, 17,
       63, 97, 73])

In [61]:
# Set seed to reproduce the results of a previous operation

np.random.seed(555) # seed needs to be in the same cell as the operation to work
np.random.rand(4)

array([0.71783409, 0.04785513, 0.94447198, 0.68638004])

Array attributes and methods

In [78]:
ranarray = np.random.randint(0, 50, 12)
ranarray

array([17,  4, 41, 12, 49,  1,  8, 20, 27, 29, 32, 49])

In [79]:
ranarray.reshape(2, 6) # Number of elements has to match the size of the original array

array([[17,  4, 41, 12, 49,  1],
       [ 8, 20, 27, 29, 32, 49]])

In [80]:
ranarray.reshape(3, 4)

array([[17,  4, 41, 12],
       [49,  1,  8, 20],
       [27, 29, 32, 49]])

In [81]:
ranarray.reshape(4, 3)

array([[17,  4, 41],
       [12, 49,  1],
       [ 8, 20, 27],
       [29, 32, 49]])

In [82]:
ranarray.reshape(12, 1)
ranarray.reshape(1, 12)

array([[17,  4, 41, 12, 49,  1,  8, 20, 27, 29, 32, 49]])

Max, Min, ArgMax, ArgMin

In [83]:
ranarray.max()

49

In [84]:
ranarray.min()

1

In [88]:
ranarray.argmax() # The index of the max is index location 4

4

In [89]:
ranarray.argmin() # The index of the min is index location 5

5

Type of Data in Array

In [91]:
ranarray.dtype

dtype('int64')

In [92]:
type(ranarray)

numpy.ndarray