In [3]:
import numpy as np

In [4]:
my_list = [1, 2, 3]
type(my_list)

list

In [5]:
np.array(my_list)
type(my_list)

array([1, 2, 3])

In [15]:
# Assign the tuple to arr and cast to a Numpy array
arr = np.array(my_list)
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [16]:
#Transform a nested list into a Numpy Matrix array

my_list = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
my_list

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [17]:
# Cast this into an np array 2 dimensional matrix 
np.array(my_list)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [18]:
my_matrix = np.array(my_list)
my_matrix.shape

(3, 3)

In [23]:
# Create a Range / Linearly Spaced and Random Numbers

np.arange(0, 20, 2) # Start stop step

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [25]:
np.ones(5) # Provides a range of floating point numbers 
np.zeros((4, 10)) # Passing in a range of tuples - 4 rows and 10 columns of zeros

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [26]:
# Broadcasting is massive in Numpy

np.ones((5,5)) + 4

array([[5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.]])

In [28]:
np.ones(4)
np.ones(4) * 100

array([100., 100., 100., 100.])

In [33]:
[1,1,1,1] * 2 # A plain python list will not perform the operation 

[1, 1, 1, 1, 1, 1, 1, 1]

In [34]:
np.array([1,1,1,1]) * 100

array([100, 100, 100, 100])

In [35]:
np.linspace(0, 20, 3) # Create a linear spaced array with a start a stop number and a step. Note these are inclusive. So start and stop numbers are included

array([ 0., 10., 20.])