In [1]:
import numpy as np

In [2]:
arr = np.arange(0,10)

In [5]:
# Element wise arithmetic on an array
arr + 20 
arr ** 2
arr / 3

array([0.        , 0.33333333, 0.66666667, 1.        , 1.33333333,
       1.66666667, 2.        , 2.33333333, 2.66666667, 3.        ])

In [7]:
# Array based operations

arr + arr


array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [8]:
arr * arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [11]:
arr / arr**2 # Here again we see zero elements being squared. Warning provided

/Applications/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([       nan, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [12]:
1 / arr # it will give an output but it will also provide a warning - divide by zero

/Applications/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

Universal Array functions
---

In [14]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [15]:
np.sum(arr)

45

In [21]:
np.mean(arr)

4.5

In [23]:
np.var(arr)

8.25

In [17]:
np.log(arr)

/Applications/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [19]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [20]:
np.cos(arr)

array([ 1.        ,  0.54030231, -0.41614684, -0.9899925 , -0.65364362,
        0.28366219,  0.96017029,  0.75390225, -0.14550003, -0.91113026])

In [41]:
# there is a logic here. When working with 2 dimensions you may just want the scalar output such as sum or mean

arr_2d = np.array([[1,2,3,4], [5,2,4,7], [1,3,5,2], [9,5,6,7]])
arr_2d # here we see the 2 dimensional array 

array([[1, 2, 3, 4],
       [5, 2, 4, 7],
       [1, 3, 5, 2],
       [9, 5, 6, 7]])

In [42]:
arr_2d.dtype

dtype('int64')

In [43]:
arr_2d.shape # 4 rows, 4 columns

(4, 4)

In [44]:
arr_2d.sum()

66

In [45]:
arr_2d.sum(axis=0) # Give me the sum across the rows, but give me the value in the columns

array([16, 12, 18, 20])

In [46]:
arr_2d.sum(axis=1) # Give me the sum across the columns, but give me the value in the rows

array([10, 18, 11, 27])

In [47]:
arr_2d.mean()

4.125