In [93]:
import numpy as np

Indexing in Numpy
---

In [98]:
arr = np.arange(1, 100, 2)
arr

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
       69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

In [102]:
arr[21] # Grab a single value by placing square braces around the target index location


array([], dtype=int64)

In [106]:
arr[12:28]

array([25, 27, 29, 31, 33, 35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55])

In [107]:
arr[12:]

array([25, 27, 29, 31, 33, 35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57,
       59, 61, 63, 65, 67, 69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91,
       93, 95, 97, 99])

In [108]:
arr[-12]

77

In [110]:
arr[::]

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
       69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

Broadcasting & Index Slicing
---

In [112]:
arr + 100

array([101, 103, 105, 107, 109, 111, 113, 115, 117, 119, 121, 123, 125,
       127, 129, 131, 133, 135, 137, 139, 141, 143, 145, 147, 149, 151,
       153, 155, 157, 159, 161, 163, 165, 167, 169, 171, 173, 175, 177,
       179, 181, 183, 185, 187, 189, 191, 193, 195, 197, 199])

In [113]:
arr / 3

array([ 0.33333333,  1.        ,  1.66666667,  2.33333333,  3.        ,
        3.66666667,  4.33333333,  5.        ,  5.66666667,  6.33333333,
        7.        ,  7.66666667,  8.33333333,  9.        ,  9.66666667,
       10.33333333, 11.        , 11.66666667, 12.33333333, 13.        ,
       13.66666667, 14.33333333, 15.        , 15.66666667, 16.33333333,
       17.        , 17.66666667, 18.33333333, 19.        , 19.66666667,
       20.33333333, 21.        , 21.66666667, 22.33333333, 23.        ,
       23.66666667, 24.33333333, 25.        , 25.66666667, 26.33333333,
       27.        , 27.66666667, 28.33333333, 29.        , 29.66666667,
       30.33333333, 31.        , 31.66666667, 32.33333333, 33.        ])

In [114]:
arr ** 3

array([     1,     27,    125,    343,    729,   1331,   2197,   3375,
         4913,   6859,   9261,  12167,  15625,  19683,  24389,  29791,
        35937,  42875,  50653,  59319,  68921,  79507,  91125, 103823,
       117649, 132651, 148877, 166375, 185193, 205379, 226981, 250047,
       274625, 300763, 328509, 357911, 389017, 421875, 456533, 493039,
       531441, 571787, 614125, 658503, 704969, 753571, 804357, 857375,
       912673, 970299])

In [115]:
arr ^ 12

array([ 13,  15,   9,  11,   5,   7,   1,   3,  29,  31,  25,  27,  21,
        23,  17,  19,  45,  47,  41,  43,  37,  39,  33,  35,  61,  63,
        57,  59,  53,  55,  49,  51,  77,  79,  73,  75,  69,  71,  65,
        67,  93,  95,  89,  91,  85,  87,  81,  83, 109, 111])

In [116]:
arr * 43

array([  43,  129,  215,  301,  387,  473,  559,  645,  731,  817,  903,
        989, 1075, 1161, 1247, 1333, 1419, 1505, 1591, 1677, 1763, 1849,
       1935, 2021, 2107, 2193, 2279, 2365, 2451, 2537, 2623, 2709, 2795,
       2881, 2967, 3053, 3139, 3225, 3311, 3397, 3483, 3569, 3655, 3741,
       3827, 3913, 3999, 4085, 4171, 4257])

In [118]:
np.sqrt(arr)

array([1.        , 1.73205081, 2.23606798, 2.64575131, 3.        ,
       3.31662479, 3.60555128, 3.87298335, 4.12310563, 4.35889894,
       4.58257569, 4.79583152, 5.        , 5.19615242, 5.38516481,
       5.56776436, 5.74456265, 5.91607978, 6.08276253, 6.244998  ,
       6.40312424, 6.55743852, 6.70820393, 6.8556546 , 7.        ,
       7.14142843, 7.28010989, 7.41619849, 7.54983444, 7.68114575,
       7.81024968, 7.93725393, 8.06225775, 8.18535277, 8.30662386,
       8.42614977, 8.54400375, 8.66025404, 8.77496439, 8.88819442,
       9.        , 9.11043358, 9.21954446, 9.32737905, 9.43398113,
       9.53939201, 9.64365076, 9.74679434, 9.8488578 , 9.94987437])

In [161]:
#np.max(arr); np.argmin(arr); np.argmax(arr); np.argmin(arr)

0

In [130]:
# A slice will still point to the original array

In [132]:
slice_of_array = arr[12:27]

In [133]:
slice_of_array[:] = 99

In [134]:
slice_of_array

array([99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99])

In [135]:
arr # Notice that the elements have changed where I broadcast a reassignment into the original array

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 99, 99, 99, 99, 99,
       99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 55, 57, 59, 61, 63, 65, 67,
       69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

In [136]:
arr_copy = arr.copy()

In [141]:
arr_copy[:] = 10_000 # this copies the new value into every index space in the array I copied

In [142]:
arr_copy

array([10000, 10000, 10000, 10000, 10000, 10000, 10000, 10000, 10000,
       10000, 10000, 10000, 10000, 10000, 10000, 10000, 10000, 10000,
       10000, 10000, 10000, 10000, 10000, 10000, 10000, 10000, 10000,
       10000, 10000, 10000, 10000, 10000, 10000, 10000, 10000, 10000,
       10000, 10000, 10000, 10000, 10000, 10000, 10000, 10000, 10000,
       10000, 10000, 10000, 10000, 10000])

In [147]:
# Create a 2D matrix

arr_2d = np.array([[5,10,15], [20,25,30], [30,40,45]])
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [30, 40, 45]])

In [148]:
arr_2d.shape

(3, 3)

In [149]:
arr_2d[1]

array([20, 25, 30])

In [152]:
arr_2d[1][1] 
#or alternatively
arr_2d[1,1]

25

In [153]:
arr_2d[2][2]

45

In [160]:
# Selection of more than one number 10, 15, 25, 30
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

Conditional Selection
---

In [173]:
#Very important in Pandas when filtering based on boolean comparisons

bool_14 = arr > 14
bool_14

array([False, False, False, False, False, False, False,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True])

In [174]:
arr[bool_14] # Passing in the boolean array - passes in where the index was true

array([15, 17, 19, 21, 23, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99,
       99, 99, 99, 55, 57, 59, 61, 63, 65, 67, 69, 71, 73, 75, 77, 79, 81,
       83, 85, 87, 89, 91, 93, 95, 97, 99])

In [177]:
# All done in one step - very common in Pandas

arr[arr % 3 == 0] # Doing a simple modulo condition

array([ 3,  9, 15, 21, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99,
       99, 99, 57, 63, 69, 75, 81, 87, 93, 99])